### ISSUE TITLE
404 page missing

### ISSUE THREAD

**Issue by adamrneary** [activecell/activecell.com#11]

**Comment by adamrneary** [comment]
Blank slate on this, sir. If you could design us a simple 404 page, that would be awesome. Let's not use the term "404" in the page since no one knows what that means outside of the tech world. Basecamp has a good example.

http://basecamp.com/crazysauce

**Comment by fcjne** [comment]
Adam, I just added 404 page with a recent commit, please check.
Also, I think we will need to change content a bit, because I made a copy of texts from the Basecamp 404 page.

**Comment by adamrneary** [comment]
Done and done
