### ISSUE TITLE
Get experts stuff working

### ISSUE THREAD

**Issue by lucassus** [activecell/activecell.com#16]
"experts" and "authors" are really the same concept here. An expert's profile is just a category of post (see two folders--blog and expert). Each blog post, though, has an "author" that is one of the experts. That's all it is.

Obviously, once this is complete, we should be able to add 20 experts quickly just by adding 1 expert post for each. Then we could add 100 articles in the next couple months if we had to, each one associated with an expert.

Six months from now, we might have a volume that would justify converting this site to a rails app and using DBs rather than directories of md files, but for now I think it's fine.

Here's the task list for remaining expert functionality:
1. anywhere we have a list of blog posts, it should NOT include expert profiles (i.e. should be filtered to blog category)
2. expert list (http://www.activecell.com/experts.html) should display all experts if the subnav has "ALL" active (default state) or filter based on the tags; see how we filter blog posts for excerpts () and implement similarly
3. expert profile (e.g. http://www.activecell.com/2012/11/hill.html) needs to display only articles by that author (limit 10). in the future, we will need a way to paginate articles by an expert, but not something to worry about yet.
4. blog index (http://www.activecell.com/blog.html) need to display all authors in the sidebar with avatars linking to their url; blog previews should have linked avatars, and name in "posted by" should be a link
5. blog show (e.g. http://www.activecell.com/2012/11/staffing.html) should link from the avatar and "posted by" but should also include the author's excerpt at the bottom under an "About the Author" h2 
6. Extra credit: Make the "featured" experts on http://www.activecell.com/#experts dynamic based on the first 5 experts with "featured" as a category (or whatever). Not worth getting into if it's more than an hour's work.

**Comment by adamrneary** [comment]
wasn't sure if i wanted to track issues in each of the different repos, but i guess for now it's fine...

**Comment by adamrneary** [comment]
@lucassus desc updated. see if this makes sense?
